name: build

on:
  push:
    branches:
    - main

defaults:
  run:
    shell: bash
jobs:
  trigger-build:
    name: Trigger build
    runs-on: ubuntu-latest
    steps:
      - name: sleep for 30 seconds
        run: sleep 30s
        shell: bash
      - name: hit endpoint  
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/64c0e6ee7dfcba46046efe99
